backend:
  name: github
  repo: rohgat/gattu-website
  branch: main

media_folder: public/uploads
public_folder: /uploads
publish_mode: editorial_workflow

collections:
  - name: books
    label: Books
    folder: src/content/posts/books
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: frontmatter
    fields: &post_fields
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDate, widget: datetime, date_format: YYYY-MM-DD, time_format: false }
      - { label: Category, name: category, widget: hidden, default: books }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Featured Image, name: image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
  - name: musings
    label: Musings
    folder: src/content/posts/musings
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDate, widget: datetime, date_format: YYYY-MM-DD, time_format: false }
      - { label: Category, name: category, widget: hidden, default: musings }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Featured Image, name: image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
  - name: memes
    label: Memes
    folder: src/content/posts/memes
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDate, widget: datetime, date_format: YYYY-MM-DD, time_format: false }
      - { label: Category, name: category, widget: hidden, default: memes }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Featured Image, name: image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
  - name: etc
    label: Etc.
    folder: src/content/posts/etc
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDate, widget: datetime, date_format: YYYY-MM-DD, time_format: false }
      - { label: Category, name: category, widget: hidden, default: etc }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Featured Image, name: image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
